// SpecialButton - Generated by Kotlin conversion
package termux.shared.termux.extrakeys

/** The [Class] that implements special buttons for [ExtraKeysView]. */
class SpecialButton(val key: String) {

    companion object {
        private val map = mutableMapOf<String, SpecialButton>()

        @JvmField
        val CTRL = SpecialButton("CTRL")

        @JvmField
        val ALT = SpecialButton("ALT")

        @JvmField
        val SHIFT = SpecialButton("SHIFT")

        @JvmField
        val FN = SpecialButton("FN")

        /**
         * Get the [SpecialButton] for `key`.
         *
         * @param key The unique key name for the special button.
         */
        @JvmStatic
        fun valueOf(key: String?): SpecialButton? = map[key]
    }

    init {
        map[key] = this
    }

    override fun toString(): String = key
}
